### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#171]
Below is my failing test. CDRS works (can connect and send queries), but not this driver. I am using Windows 10 and ScyllaDB is running in Docker. The test is not running in Docker. 

This is how I start a ScyllaDB instance in Docker:

`$ docker run --name db -p 127.0.0.1:9042:9042 -p 127.0.0.1:9160:9160 -d scylladb/scylla`

And this is my test

```
mod test {
    use cdrs::cluster::{NodeTcpConfigBuilder, ClusterTcpConfig, session};
    use cdrs::load_balancing::RoundRobin;
    use cdrs::query::QueryExecutor;
    use cdrs::authenticators::NoneAuthenticator;
    use scylla::SessionBuilder;

    #[tokio::test]
    async fn goo() {
        let node = NodeTcpConfigBuilder::new("127.0.0.1:9042", NoneAuthenticator {})
            .build();
        let cluster_config = ClusterTcpConfig(vec![node]);
        let session = session::new(&cluster_config, RoundRobin::new()).unwrap();
        let _ = session.query("SELECT * FROM system_schema.keyspaces").unwrap();

        let session = SessionBuilder::new()
            .known_node("127.0.0.1:9042")
            .build()
            .await
            .unwrap();

        let _ = session.query("SELECT * FROM system_schema.keyspaces", &[]).await.unwrap().unwrap();
    }
}
```

This is the error:

```
called `Result::unwrap()` on an `Err` value: IOError(Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." })
thread 'test::goo' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." })', src\main.rs:22:83
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed\/library\core\src\option.rs:1266
   3: core::result::Result<core::option::Option<alloc::vec::Vec<scylla::frame::response::result::Row, alloc::alloc::Global>>, scylla::transport::errors::QueryError>::unwrap<core::option::Option<alloc::vec::Vec<scylla::frame::response::result::Row, alloc::alloc:
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:969
   4: fortesting::test::goo::{{closure}}
             at .\src\main.rs:22
   5: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   6: core::future::future::{{impl}}::poll<mut core::future::from_generator::GenFuture<generator-0>*>
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\future.rs:119
   7: tokio::runtime::basic_scheduler::{{impl}}::block_on::{{closure}}::{{closure}}<tokio::runtime::driver::Driver,core::pin::Pin<mut core::future::from_generator::GenFuture<generator-0>*>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:184
   8: tokio::coop::with_budget::{{closure}}<core::task::poll::Poll<tuple<>>,closure-0>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\coop.rs:121
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  10: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<tuple<>>>
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  11: tokio::coop::with_budget
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\coop.rs:114
  12: tokio::coop::budget
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\coop.rs:98
  13: tokio::runtime::basic_scheduler::{{impl}}::block_on::{{closure}}<tokio::runtime::driver::Driver,core::pin::Pin<mut core::future::from_generator::GenFuture<generator-0>*>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:184
  14: tokio::runtime::basic_scheduler::enter::{{closure}}<closure-0,tuple<>,tokio::runtime::driver::Driver>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:266
  15: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::basic_scheduler::Context>::set<tokio::runtime::basic_scheduler::Context,closure-0,tuple<>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\macros\scoped_tls.rs:61
  16: tokio::runtime::basic_scheduler::enter<closure-0,tuple<>,tokio::runtime::driver::Driver>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:266
  17: tokio::runtime::basic_scheduler::Inner<tokio::runtime::driver::Driver>::block_on<tokio::runtime::driver::Driver,core::pin::Pin<mut core::future::from_generator::GenFuture<generator-0>*>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:176
  18: tokio::runtime::basic_scheduler::InnerGuard<tokio::runtime::driver::Driver>::block_on<tokio::runtime::driver::Driver,core::pin::Pin<mut core::future::from_generator::GenFuture<generator-0>*>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:405
  19: tokio::runtime::basic_scheduler::BasicScheduler<tokio::runtime::driver::Driver>::block_on<tokio::runtime::driver::Driver,core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\basic_scheduler.rs:136
  20: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\javisser\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\mod.rs:450
  21: fortesting::test::goo
             at .\src\main.rs:8
  22: fortesting::test::goo::{{closure}}
             at .\src\main.rs:8
  23: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\javisser\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  24: core::ops::function::FnOnce::call_once
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by piodul** [comment]
I confirm, I reproduced this issue yesterday on my Windows 10 installation. When running examples or tests from the latest `main` (075ad419649984b7d901ae04b8bfa56783340095), they hang for a while and then fail with the same error. I bisected the main branch and it looks like it started happening since d4330ef51098329e0dbdb95d4886158fb5b5983c was introduced.

I also tried the same test on Fedora and it worked correctly.

**Comment by cvybhu** [comment]
I reproduced the issue between a Windows 10 VM and a Linux VM running scylla with docker.
I had some trouble running Docker on a Windows 10 VM because it requires to run a VM inside a VM.
The error is the same so this should probably be fine.

Looking at the logs it seems that what happens is this:
1) We create a control connection to `127.0.0.1:9042` and query cluster topology information
2) We query `rpc_address` from `system.local` which turns out to be `172.17.0.2` - the local address inside Docker
3) We try to connect to this internal docker address `172.17.0.2` - on linux this works, on windows probably fails (at least between VMs it fails)

There was some discussion about querying address from `system.local` in #154 - it was said that we should use the existing connection's address insted of querying it when SNI is not set.

I will fix it and open a PR.

**Comment by Jasperav** [comment]
This is fixed, thanks @cvybhu
