### ISSUE TITLE
the trait bound `scylla::frame::value::Timestamp: FromCqlVal<CqlValue>` is not satisfied

### ISSUE THREAD

**Issue by Y0ngg4n** [scylladb/scylla-rust-driver#245]
Source Code: https://github.com/Y0ngg4n/fluffy_rest_api

```
error[E0277]: the trait bound `scylla::frame::value::Timestamp: FromCqlVal<CqlValue>` is not satisfied
  --> src/db/models/user.rs:21:5
   |
21 |     pub created: Timestamp,
   |     ^^^ the trait `FromCqlVal<CqlValue>` is not implemented for `scylla::frame::value::Timestamp`
   |
   = note: required because of the requirements on the impl of `FromCqlVal<std::option::Option<CqlValue>>` for `scylla::frame::value::Timestamp`
   = note: required by `from_cql`
```

**Comment by cvybhu** [comment]
When receiving values use `chrono::Duration`
`Timestamp` is a wrapper around `chrono::Duration` which is only used for sending.

Here is the documentation about using `Timestamp`:
https://cvybhu.github.io/scyllabook/data-types/timestamp.html


Maybe making `Timestamp` receiveable in the future would be a good idea, but for now only `chrono::Duration` is.

**Comment by Y0ngg4n** [comment]
@cvybhu Thank you for your quick response. I changed it in the [code](https://github.com/Y0ngg4n/fluffy_rest_api.git) to duration but getting this error now:
:
```
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: BadCqlVal(BadCqlType)', src/api/account.rs:40:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: core::result::Result<T,E>::unwrap
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: <fluffy_rest_api::api::account::login as actix_web::service::HttpServiceFactory>::register::login::{{closure}}
             at ./src/api/account.rs:40:28
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/handler.rs:138:15
   7: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/handler.rs:247:20
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/map.rs:55:37
   9: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/lib.rs:93:13
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  12: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/either.rs:90:33
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  14: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/either.rs:89:32
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  16: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/middleware/logger.rs:285:46
  17: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/h1/dispatcher.rs:400:54
  18: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/h1/dispatcher.rs:783:38
  19: actix_http::service::State<T,S,B,X,U>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/service.rs:682:36
  20: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/service.rs:661:9
  21: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101:34
  22: <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85:33
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  24: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  26: tokio::runtime::task::core::Core<T,S>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  27: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  28: core::ops::function::FnOnce::call_once
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  30: std::panicking::try::do_call
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  31: __rust_try
  32: std::panicking::try
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  33: std::panic::catch_unwind
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  34: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  35: tokio::runtime::task::raw::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  36: tokio::runtime::task::raw::RawTask::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  37: tokio::runtime::task::Notified<S>::run
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  38: tokio::task::local::LocalSet::tick::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:54
  39: tokio::coop::with_budget::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  40: std::thread::local::LocalKey<T>::try_with
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  41: std::thread::local::LocalKey<T>::with
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  42: tokio::coop::with_budget
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  43: tokio::coop::budget
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  44: tokio::task::local::LocalSet::tick
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:31
  45: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:532:16
  46: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  47: tokio::task::local::LocalSet::with
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:442:9
  48: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:518:9
  49: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:392:9
  50: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  51: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:58
  52: tokio::coop::with_budget::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  53: std::thread::local::LocalKey<T>::try_with
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  54: std::thread::local::LocalKey<T>::with
             at /home/yonggan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  55: tokio::coop::with_budget
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  56: tokio::coop::budget
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  57: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:35
  58: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:29
  59: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  60: tokio::runtime::basic_scheduler::enter
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:5
  61: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:123:9
  62: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:444:34
  63: tokio::runtime::context::enter
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  64: tokio::runtime::handle::Handle::enter
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  65: tokio::runtime::Runtime::block_on
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:441:9
  66: tokio::task::local::LocalSet::block_on
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:353:9
  67: actix_rt::runtime::Runtime::block_on
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  68: actix_rt::arbiter::Arbiter::new::{{closure}}
             at /home/yonggan/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cvybhu** [comment]
The `BadCqlType` error occurs when the received row element has different type than expected.
(For example when the driver received an `int` but was expecting `text`)

Could you check if each type in your struct matches exactly the selected columns.
Number and order of struct fields must exactly match the selected row elements.

Here is more [documentation](https://cvybhu.github.io/scyllabook/queries/result.html#parsing-row-as-a-custom-struct) about receiving rows to structs

**Comment by Y0ngg4n** [comment]
@cvybhu Ok got it the order was wrong. But i have a question. I have created my table with this SQL query:
```rust
 session
        .query(
            "CREATE TABLE IF NOT EXISTS fluffy_board.account ( \
            id UUID, \
            name text, \
            email text, \
            password text,\
            created timestamp, \
            PRIMARY KEY(id, email))",
            &[],
        )
        .await?;
```
But i got a wrong order of fields in my table:
![image](https://user-images.githubusercontent.com/30302975/120068615-d1511c00-c081-11eb-8198-060aa6fa92ee.png)

How can i prevent this?

**Comment by psarna** [comment]
That's just how Scylla/Cassandra works - the order is important for the keys, but regular columns will be presented in arbitrary order in cqlsh when you send "SELECT *" (expect them to just be presented lexicographically). When you ask for specific columns in your SELECT query, the results will be ordered in the same order as in the query.

**Comment by Y0ngg4n** [comment]
@psarna Thank you for your answer you helped me a lot :)
