### ISSUE TITLE
Some inputs cannot be compressed with LZ4

### ISSUE THREAD

**Issue by crestonbunch** [scylladb/scylla-rust-driver#381]
I believe this is possibly a bug with the compress crate, but I think it's also partly Scylla's fault because it works most of the time. Under certain circumstances it is possible to craft inputs that fail.

Anyways, here is an example of something that will result in a 'attempt to subtract with overflow' error. I ran this test in frame/mod.rs

```
#[test]
fn breaking_example() {
    let mut out = Vec::new();
    let uncomp_body = b"\0\x10\x0c>\xe5J\x02\xef\x02h|\x99X\xf8L\x80<\t\0\x04\x11\0\x08\0\0\0@\0\0\0\rEmailPassword\0\0\0+Fetjn3VkIyBYOYAEDIEJ66ft7zC11zFc9u2QrqVz8FM\0\0\0\x06abc123\xff\xff\xff\xfe\0\0\0T$argon2i$v=19$m=4096,t=3,p=1$V29lP3EnIyA$Rjc9n2+d6/ruKvYiL0ivDv9zj+A5QLJbawc5qYHIZAc\0\0\0\x01\0\xff\xff\xff\xfe\xff\xff\xff\xfe\0\0\0\x04\0\0!\x98\0\t";
    let compression = Compression::Lz4;
    compress_append(uncomp_body, compression, &mut out).unwrap();
}
```

That's the root cause. But to get to that point you need to craft input that produces that uncompressed body. Here is how I did it:

This breaks on the 'INSERT' query.

Interesting, it works if you remove the TTL.

```rust
let port = 9042;
let builder = SessionBuilder::new()
    .compression(Some(Compression::Lz4))
    .known_node(format!("localhost:{}", port));

let session = builder.build().await.unwrap();

session
    .query("CREATE KEYSPACE IF NOT EXISTS auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}", &[])
    .await
    .unwrap();

session.use_keyspace("auth", true).await.unwrap();

session
    .query(
        r#"
    CREATE TABLE IF NOT EXISTS challenges (
        identifier          tuple<text, text>,
        user_id             text,
        challenge_hash      text,
        activated           boolean,
        expires_at          timestamp,
        failed_attempts     int,
        previous_challenge  tuple<text, text>,
        PRIMARY KEY (identifier)
    )"#,
        &[],
    )
    .await
    .unwrap();

let prepared = session
    .prepare(
        r#"
    INSERT INTO challenges (
        identifier,
        user_id,
        previous_challenge,
        challenge_hash,
        activated,
        expires_at,
        failed_attempts
    ) VALUES (?, ?, ?, ?, ?, ?, ?) USING TTL ?
"#,
    )
    .await
    .unwrap();

let tuple: (
    (String, String),
    String,
    MaybeUnset<(String, String)>,
    String,
    bool,
    MaybeUnset<Timestamp>,
    MaybeUnset<i64>,
    i32,
) = (
    ("EmailPassword".into(), "abc123".into()),
    "user@example.com".into(),
    MaybeUnset::Unset,
    "$argon2i$v=19$m=4096,t=3,p=1$s+IV/IW//yA$TuMaZSBPC5VLaBrE4BkCLjryYqmYNwoGLrg/Lh2obbY".into(),
    false,
    MaybeUnset::Unset,
    MaybeUnset::Unset,
    3600,
);
session
    .execute(
        &prepared,
        tuple,
    )
    .await
    .unwrap();
```

Stack trace:

```
thread 'stores::tests::test_breaking_case' panicked at 'attempt to subtract with overflow', /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/compress-0.2.1/src/lz4.rs:265:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/panicking.rs:48:5
   3: compress::lz4::BlockEncoder::encode
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/compress-0.2.1/src/lz4.rs:265:58
   4: compress::lz4::encode_block
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/compress-0.2.1/src/lz4.rs:626:5
   5: scylla::frame::compress_append
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/frame/mod.rs:212:13
   6: scylla::frame::SerializedRequest::make
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/frame/mod.rs:53:13
   7: scylla::transport::connection::Connection::send_request::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/connection.rs:634:34
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
   9: scylla::transport::connection::Connection::execute::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/connection.rs:446:30
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  11: scylla::transport::session::Session::execute_paged::{{closure}}::{{closure}}::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/session.rs:659:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  13: scylla::transport::session::Session::execute_query::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/session.rs:1097:62
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  15: scylla::transport::session::Session::run_query::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/session.rs:1052:18
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  17: scylla::transport::session::Session::execute_paged::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/session.rs:653:24
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  19: scylla::transport::session::Session::execute::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/scylla-0.3.1/src/transport/session.rs:627:9
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  21: auth::stores::tests::test_breaking_case::{{closure}}::{{closure}}
             at ./src/stores.rs:433:13
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/mod.rs:80:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/future/future.rs:119:9
  24: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
  25: tokio::coop::with_budget::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  26: std::thread::local::LocalKey<T>::try_with
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/thread/local.rs:399:16
  27: std::thread::local::LocalKey<T>::with
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/thread/local.rs:375:9
  28: tokio::coop::with_budget
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  29: tokio::coop::budget
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  30: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  31: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  32: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  33: tokio::runtime::basic_scheduler::enter
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  34: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  35: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  36: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:186:24
  37: tokio::runtime::Runtime::block_on
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  38: tokio_test::block_on
             at /home/creston/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-test-0.4.2/src/lib.rs:35:5
  39: auth::stores::tests::run_test::{{closure}}
             at ./src/stores.rs:287:45
  40: std::panicking::try::do_call
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/panicking.rs:406:40
  41: __rust_try
  42: std::panicking::try
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/panicking.rs:370:19
  43: std::panic::catch_unwind
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/panic.rs:133:14
  44: auth::stores::tests::run_test
             at ./src/stores.rs:287:22
  45: auth::stores::tests::test_breaking_case
             at ./src/stores.rs:354:9
  46: auth::stores::tests::test_breaking_case::{{closure}}
             at ./src/stores.rs:353:5
  47: core::ops::function::FnOnce::call_once
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/ops/function.rs:227:5
  48: core::ops::function::FnOnce::call_once
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by crestonbunch** [comment]
I have created a PR to fix this by allowing the use of a different LZ4 compression crate: #380, and I have confirmed that the above failing test case works with the new crate on my PR branch.
