### ISSUE TITLE
Testing instructions in contributing.md results in 49 failures on main branch

### ISSUE THREAD

**Issue by junglie85** [scylladb/scylla-rust-driver#465]
The [instructions for testing the driver](https://github.com/scylladb/scylla-rust-driver/blob/c92e0923c076c6636fbac8f1d03b53ceff0905b4/CONTRIBUTING.md?plain=1#L31-L44) results in 49 failed tests on `main` branch at commit 9d402a9.

System info:

```
System Version: macOS 12.4 (21F79)
Kernel Version: Darwin 21.5.0
Model Identifier: MacBookPro17,1
Chip: Apple M1
```

I've previously had problems running the Scylla docker image on the M1, which was resolved by using a dev image `scylladb/scylla:4.6.dev-0.20210801.3089558f8`. I've tried with this image too, which I use successfully in another project, but which fails here. I don't think it should be necessary to use this dev image on the M1 anymore given that 5.x is now published.

Following the instructions results in:

```
junglie85@mbp ~/d/s/docker (pub-partitioner) [101]> SCYLLA_URI="(docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042" cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.26s
     Running unittests src/lib.rs (/Users/junglie85/dev/scylla-rust-driver/target/debug/deps/scylla-859a32c3d20f8eb5)

running 194 tests
test frame::cql_collections_test::test_cql_list ... FAILED
test frame::cql_types_test::test_date ... FAILED
test frame::cql_collections_test::test_cql_map ... FAILED
test frame::cql_collections_test::test_cql_set ... FAILED
test frame::cql_types_test::test_bool ... FAILED
test frame::cql_types_test::test_blob ... FAILED
test frame::cql_collections_test::test_cql_tuple ... FAILED
test frame::cql_types_test::test_counter ... FAILED
test frame::cql_types_test::test_float ... FAILED
test frame::cql_types_test::test_naive_date ... FAILED
test frame::cql_types_test::test_decimal ... FAILED
test frame::cql_types_test::test_empty ... FAILED
test frame::response::cql_to_rust::tests::counter_from_cql ... ok
test frame::cql_types_test::test_inet ... FAILED
test frame::response::cql_to_rust::tests::bool_from_cql ... ok
test frame::response::cql_to_rust::tests::floatingpoints_from_cql ... ok
test frame::response::cql_to_rust::tests::from_cql_empty_value ... ok
test frame::response::cql_to_rust::tests::duration_from_cql ... ok
test frame::cql_types_test::test_time ... FAILED
test frame::response::cql_to_rust::tests::from_cql_null ... ok
test frame::response::cql_to_rust::tests::from_cql_wrong_type ... ok
test frame::response::cql_to_rust::tests::from_row_too_large ... ok
test frame::response::cql_to_rust::tests::from_row_null ... ok
test frame::response::cql_to_rust::tests::from_row_too_short ... ok
test frame::response::cql_to_rust::tests::i16_from_cql ... ok
test frame::response::cql_to_rust::tests::i32_from_cql ... ok
test frame::response::cql_to_rust::tests::i64_from_cql ... ok
test frame::response::cql_to_rust::tests::i8_from_cql ... ok
test frame::response::cql_to_rust::tests::ip_addr_from_cql ... ok
test frame::response::cql_to_rust::tests::from_row_wrong_type ... ok
test frame::response::cql_to_rust::tests::string_from_cql ... ok
test frame::response::cql_to_rust::tests::naive_date_from_cql ... ok
test frame::response::cql_to_rust::tests::struct_from_row_wrong_size ... ok
test frame::response::cql_to_rust::tests::time_from_cql ... ok
test frame::cql_types_test::test_timeuuid ... FAILED
test frame::response::cql_to_rust::tests::timestamp_from_cql ... ok
test frame::response::cql_to_rust::tests::tuple_from_row ... ok
test frame::response::cql_to_rust::tests::uuid_from_cql ... ok
test frame::response::cql_to_rust::tests::decimal_from_cql ... ok
test frame::response::cql_to_rust::tests::varint_from_cql ... ok
test frame::cql_types_test::test_udt_after_schema_update ... FAILED
test frame::response::cql_to_rust::tests::vec_from_cql ... ok
test frame::response::cql_to_rust::tests::struct_from_row ... ok
test frame::cql_types_test::test_timestamp ... FAILED
test frame::response::error::tests::deserialize_read_failure ... ok
test frame::response::error::tests::deserialize_unavailable ... ok
test frame::response::error::tests::deserialize_read_timeout ... ok
test frame::response::error::tests::deserialize_simple_errors ... ok
test frame::response::error::tests::deserialize_already_exists ... ok
test frame::response::error::tests::deserialize_function_failure ... ok
test frame::response::error::tests::deserialize_write_failure ... ok
test frame::response::error::tests::deserialize_write_timeout ... ok
test frame::cql_types_test::test_varint ... FAILED
test frame::response::result::tests::date_deserialize ... ok
test frame::response::result::tests::test_decimal ... ok
test frame::response::result::tests::test_deserialize_blob ... ok
test frame::response::result::tests::test_deserialize_bool ... ok
test frame::response::result::tests::test_deserialize_counter ... ok
test frame::response::result::tests::test_deserialize_int_types ... ok
test frame::response::result::tests::test_deserialize_text_types ... ok
test frame::response::error::tests::deserialize_unprepared ... ok
test frame::response::result::tests::test_deserialize_empty_payload ... ok
test frame::response::result::tests::test_deserialize_uuid_inet_types ... ok
test frame::response::result::tests::test_duration_deserialize ... ok
test frame::response::result::tests::test_floating_points ... ok
test frame::response::result::tests::test_list_from_cql ... ok
test frame::response::result::tests::test_map_from_cql ... ok
test frame::response::result::tests::test_serialize_empty ... ok
test frame::response::result::tests::test_set_from_cql ... ok
test frame::response::result::tests::test_time_deserialize ... ok
test frame::response::result::tests::test_timestamp_deserialize ... ok
test frame::response::result::tests::test_timeuuid_deserialize ... ok
test frame::response::result::tests::test_udt_from_cql ... ok
test frame::test::test_lz4_compress ... ok
test frame::response::result::tests::test_varint ... ok
test frame::response::cql_to_rust::tests::set_from_cql ... ok
test frame::types::type_consistency ... ok
test frame::types::type_bytes_map ... ok
test frame::types::type_inet ... ok
test frame::test::test_lz4_decompress ... ok
test frame::types::type_int ... ok
test frame::types::type_long ... ok
test frame::types::type_long_string ... ok
test frame::types::type_string ... ok
test frame::types::type_short ... ok
test frame::types::type_string_list ... ok
test frame::types::type_string_map ... ok
test frame::types::type_uuid ... ok
test frame::types::type_string_multimap ... ok
test frame::types::zig_zag_encode_test ... ok
test frame::types::zig_zag_decode_test ... ok
test frame::types::unsigned_vint_encode_and_decode_test ... ok
test frame::types::vint_encode_and_decode_test ... ok
test frame::value_tests::option_value ... ok
test frame::value_tests::empty_array_value_list ... ok
test frame::value_tests::date_serialization ... ok
test frame::value_tests::basic_serialization ... ok
test frame::value_tests::cow_serialized_values_value_list ... ok
test frame::value_tests::ref_value ... ok
test frame::value_tests::empty_serialized_values ... ok
test frame::value_tests::naive_date_serialization ... ok
test frame::value_tests::ref_batch_values ... ok
test frame::value_tests::ref_value_list ... ok
test frame::value_tests::serialized_values ... ok
test frame::value_tests::serialized_values_value_list ... ok
test frame::value_tests::slice_batch_values ... ok
test frame::value_tests::slice_value_list ... ok
test frame::value_tests::time_serialization ... ok
test frame::value_tests::timestamp_serialization ... ok
test frame::value_tests::timeuuid_serialization ... ok
test frame::value_tests::unset_value ... ok
test frame::value_tests::vec_batch_values ... ok
test frame::value_tests::unit_value_list ... ok
test transport::authenticate_test::authenticate_superuser ... ignored
test frame::value_tests::tuple_value_list ... ok
test frame::value_tests::vec_value_list ... ok
test routing::tests::test_shard_of ... ok
test frame::value_tests::tuple_batch_values ... ok
test transport::caching_session::tests::test_execute_cached ... FAILED
test frame::value_tests::test_cqlvalue_udt ... FAILED
test transport::caching_session::tests::test_full ... FAILED
test transport::errors::tests::write_type_from_str ... ok
test transport::errors::tests::dberror_full_info ... ok
test transport::caching_session::tests::test_execute_paged_cached ... FAILED
test frame::value_tests::test_cqlvalue_duration ... FAILED
test transport::load_balancing::tests::test_iter_rotation ... ok
test transport::load_balancing::tests::test_names ... ok
test transport::load_balancing::tests::test_slice_rotation ... ok
test transport::connection_pool::tests::many_connections ... FAILED
test transport::connection::tests::connection_query_all_execute_all_test ... FAILED
test transport::caching_session::tests::test_execute_iter_cached ... FAILED
test transport::load_balancing::token_aware::tests::test_token_aware_fallback_policy ... ok
test transport::load_balancing::token_aware::tests::test_token_aware_policy_with_nts ... ok
test transport::load_balancing::round_robin::tests::test_round_robin_policy ... ok
test transport::load_balancing::dc_aware_round_robin::tests::test_dc_aware_round_robin_policy ... ok
test transport::partitioner::tests::test_cdc_partitioner ... ok
test transport::load_balancing::token_aware::tests::test_token_aware_policy ... ok
test transport::partitioner::tests::test_murmur3_partitioner ... ok
test transport::query_result::tests::first_row_test ... ok
test transport::query_result::tests::first_row_typed_test ... ok
test transport::query_result::tests::maybe_first_row_test ... ok
test transport::query_result::tests::maybe_first_row_typed_test ... ok
test transport::query_result::tests::result_not_rows_test ... ok
test transport::query_result::tests::rows_num_test ... ok
test transport::query_result::tests::rows_or_empty_test ... ok
test transport::query_result::tests::rows_test ... ok
test transport::query_result::tests::rows_typed_or_empty ... ok
test transport::query_result::tests::single_row_test ... ok
test transport::query_result::tests::rows_typed_test ... ok
test transport::query_result::tests::single_row_typed_test ... ok
test transport::retry_policy::tests::default_bootstrapping ... ok
test transport::retry_policy::tests::default_idempotent_next_retries ... ok
test transport::retry_policy::tests::default_never_retries ... ok
test transport::retry_policy::tests::default_read_timeout ... ok
test transport::retry_policy::tests::default_unavailable ... ok
test transport::retry_policy::tests::default_write_timeout ... ok
test transport::session_builder::tests::add_known_node ... ok
test transport::session_builder::tests::add_known_node_addr ... ok
test transport::session_builder::tests::add_known_nodes ... ok
test transport::session_builder::tests::add_known_nodes_addr ... ok
test transport::session_builder::tests::all_features ... ok
test transport::session_builder::tests::compression ... ok
test transport::session_builder::tests::connection_timeout ... ok
test transport::session_builder::tests::default_session_builder ... ok
test transport::session_builder::tests::fetch_schema_metadata ... ok
test transport::session_builder::tests::load_balancing ... ok
test transport::session_builder::tests::tcp_nodelay ... ok
test transport::session_builder::tests::use_keyspace ... ok
test transport::session_test::test_connection_failure ... ok
test transport::session_test::test_await_schema_agreement ... FAILED
test transport::session_test::test_batch ... FAILED
test transport::session_test::test_await_timed_schema_agreement ... FAILED
test transport::session_test::test_column_kinds_in_metadata ... FAILED
test transport::session_test::test_fetch_schema_version ... FAILED
test transport::session_test::test_db_errors ... FAILED
test transport::session_test::test_fetch_system_keyspace ... FAILED
test transport::session_test::test_prepared_config ... FAILED
test transport::session_test::test_raw_use_keyspace ... FAILED
test transport::session_test::test_schema_types_in_metadata ... FAILED
test transport::session_test::test_named_bind_markers ... FAILED
test transport::session_test::test_primary_key_ordering_in_metadata ... FAILED
test transport::session_test::test_prepared_statement ... FAILED
test transport::session_test::test_prepared_partitioner ... FAILED
test transport::session_test::test_table_partitioner_in_metadata ... FAILED
test transport::session_test::test_turning_off_schema_fetching ... FAILED
test transport::session_test::test_use_keyspace ... FAILED
test transport::session_test::test_timestamp ... FAILED
test transport::session_test::test_use_keyspace_case_sensitivity ... FAILED
test transport::session_test::test_unprepared_statement ... FAILED
test transport::session_test::test_token_calculation ... FAILED
test transport::session_test::test_tracing ... FAILED
test routing::tests::test_iter_source_ports_for_shard ... ok
test transport::session_test::test_user_defined_types_in_metadata ... FAILED
test transport::topology::tests::test_cql_type_parsing ... ok

failures:

---- frame::cql_collections_test::test_cql_list stdout ----
thread 'frame::cql_collections_test::test_cql_list' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_collections_test.rs:11:71

---- frame::cql_types_test::test_date stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_date' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_collections_test::test_cql_map stdout ----
thread 'frame::cql_collections_test::test_cql_map' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_collections_test.rs:11:71

---- frame::cql_collections_test::test_cql_set stdout ----
thread 'frame::cql_collections_test::test_cql_set' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_collections_test.rs:11:71

---- frame::cql_types_test::test_bool stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_bool' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_blob stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_blob' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_collections_test::test_cql_tuple stdout ----
thread 'frame::cql_collections_test::test_cql_tuple' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_collections_test.rs:11:71

---- frame::cql_types_test::test_counter stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_counter' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- frame::cql_types_test::test_float stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_float' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_naive_date stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_naive_date' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_decimal stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_decimal' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_empty stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_empty' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_inet stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_inet' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_time stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_time' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_timeuuid stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_timeuuid' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_udt_after_schema_update stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_udt_after_schema_update' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:761:80

---- frame::cql_types_test::test_timestamp stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_timestamp' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- frame::cql_types_test::test_varint stdout ----
Connecting to (docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla-ci):19042 ...
thread 'frame::cql_types_test::test_varint' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/cql_types_test.rs:28:80

---- transport::caching_session::tests::test_execute_cached stdout ----
thread 'transport::caching_session::tests::test_execute_cached' panicked at 'Could not create session: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/caching_session.rs:172:14

---- frame::value_tests::test_cqlvalue_udt stdout ----
thread 'frame::value_tests::test_cqlvalue_udt' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/value_tests.rs:658:80

---- transport::caching_session::tests::test_full stdout ----
thread 'transport::caching_session::tests::test_full' panicked at 'Could not create session: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/caching_session.rs:172:14

---- transport::caching_session::tests::test_execute_paged_cached stdout ----
thread 'transport::caching_session::tests::test_execute_paged_cached' panicked at 'Could not create session: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/caching_session.rs:172:14

---- frame::value_tests::test_cqlvalue_duration stdout ----
thread 'frame::value_tests::test_cqlvalue_duration' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/frame/value_tests.rs:723:80

---- transport::connection_pool::tests::many_connections stdout ----
thread 'transport::connection_pool::tests::many_connections' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" }', scylla/src/transport/connection_pool.rs:1225:14

---- transport::connection::tests::connection_query_all_execute_all_test stdout ----
thread 'transport::connection::tests::connection_query_all_execute_all_test' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" }', scylla/src/transport/connection.rs:1442:22

---- transport::caching_session::tests::test_execute_iter_cached stdout ----
thread 'transport::caching_session::tests::test_execute_iter_cached' panicked at 'Could not create session: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/caching_session.rs:172:14

---- transport::session_test::test_await_schema_agreement stdout ----
thread 'transport::session_test::test_await_schema_agreement' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1064:71

---- transport::session_test::test_batch stdout ----
thread 'transport::session_test::test_batch' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:364:71

---- transport::session_test::test_await_timed_schema_agreement stdout ----
thread 'transport::session_test::test_await_timed_schema_agreement' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1072:71

---- transport::session_test::test_column_kinds_in_metadata stdout ----
thread 'transport::session_test::test_column_kinds_in_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1482:71

---- transport::session_test::test_fetch_schema_version stdout ----
thread 'transport::session_test::test_fetch_schema_version' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1057:71

---- transport::session_test::test_db_errors stdout ----
thread 'transport::session_test::test_db_errors' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:773:71

---- transport::session_test::test_fetch_system_keyspace stdout ----
thread 'transport::session_test::test_fetch_system_keyspace' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:759:71

---- transport::session_test::test_prepared_config stdout ----
thread 'transport::session_test::test_prepared_config' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1193:71

---- transport::session_test::test_raw_use_keyspace stdout ----
thread 'transport::session_test::test_raw_use_keyspace' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:706:10

---- transport::session_test::test_schema_types_in_metadata stdout ----
thread 'transport::session_test::test_schema_types_in_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1208:71

---- transport::session_test::test_named_bind_markers stdout ----
thread 'transport::session_test::test_named_bind_markers' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1677:71

---- transport::session_test::test_primary_key_ordering_in_metadata stdout ----
thread 'transport::session_test::test_primary_key_ordering_in_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1525:71

---- transport::session_test::test_prepared_statement stdout ----
thread 'transport::session_test::test_prepared_statement' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:167:71

---- transport::session_test::test_prepared_partitioner stdout ----
thread 'transport::session_test::test_prepared_partitioner' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1733:71

---- transport::session_test::test_table_partitioner_in_metadata stdout ----
thread 'transport::session_test::test_table_partitioner_in_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1571:71

---- transport::session_test::test_turning_off_schema_fetching stdout ----
thread 'transport::session_test::test_turning_off_schema_fetching' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1612:10

---- transport::session_test::test_use_keyspace stdout ----
thread 'transport::session_test::test_use_keyspace' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:529:10

---- transport::session_test::test_timestamp stdout ----
thread 'transport::session_test::test_timestamp' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1082:71

---- transport::session_test::test_use_keyspace_case_sensitivity stdout ----
thread 'transport::session_test::test_use_keyspace_case_sensitivity' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:627:10

---- transport::session_test::test_unprepared_statement stdout ----
thread 'transport::session_test::test_unprepared_statement' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:67:71

---- transport::session_test::test_token_calculation stdout ----
thread 'transport::session_test::test_token_calculation' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:468:71

---- transport::session_test::test_tracing stdout ----
thread 'transport::session_test::test_tracing' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:828:71

---- transport::session_test::test_user_defined_types_in_metadata stdout ----
thread 'transport::session_test::test_user_defined_types_in_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })', scylla/src/transport/session_test.rs:1364:71


failures:
    frame::cql_collections_test::test_cql_list
    frame::cql_collections_test::test_cql_map
    frame::cql_collections_test::test_cql_set
    frame::cql_collections_test::test_cql_tuple
    frame::cql_types_test::test_blob
    frame::cql_types_test::test_bool
    frame::cql_types_test::test_counter
    frame::cql_types_test::test_date
    frame::cql_types_test::test_decimal
    frame::cql_types_test::test_empty
    frame::cql_types_test::test_float
    frame::cql_types_test::test_inet
    frame::cql_types_test::test_naive_date
    frame::cql_types_test::test_time
    frame::cql_types_test::test_timestamp
    frame::cql_types_test::test_timeuuid
    frame::cql_types_test::test_udt_after_schema_update
    frame::cql_types_test::test_varint
    frame::value_tests::test_cqlvalue_duration
    frame::value_tests::test_cqlvalue_udt
    transport::caching_session::tests::test_execute_cached
    transport::caching_session::tests::test_execute_iter_cached
    transport::caching_session::tests::test_execute_paged_cached
    transport::caching_session::tests::test_full
    transport::connection::tests::connection_query_all_execute_all_test
    transport::connection_pool::tests::many_connections
    transport::session_test::test_await_schema_agreement
    transport::session_test::test_await_timed_schema_agreement
    transport::session_test::test_batch
    transport::session_test::test_column_kinds_in_metadata
    transport::session_test::test_db_errors
    transport::session_test::test_fetch_schema_version
    transport::session_test::test_fetch_system_keyspace
    transport::session_test::test_named_bind_markers
    transport::session_test::test_prepared_config
    transport::session_test::test_prepared_partitioner
    transport::session_test::test_prepared_statement
    transport::session_test::test_primary_key_ordering_in_metadata
    transport::session_test::test_raw_use_keyspace
    transport::session_test::test_schema_types_in_metadata
    transport::session_test::test_table_partitioner_in_metadata
    transport::session_test::test_timestamp
    transport::session_test::test_token_calculation
    transport::session_test::test_tracing
    transport::session_test::test_turning_off_schema_fetching
    transport::session_test::test_unprepared_statement
    transport::session_test::test_use_keyspace
    transport::session_test::test_use_keyspace_case_sensitivity
    transport::session_test::test_user_defined_types_in_metadata

test result: FAILED. 144 passed; 49 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.16s

error: test failed, to rerun pass '-p scylla --lib'
```

**Comment by piodul** [comment]
> ```SCYLLA_URI="(docker inspect ...```

It looks like a dollar sign is missing before the opening parenthesis, it should be `SCYLLA_URI="$(docker inspect ...`. Could you try again with this modification?

**Comment by junglie85** [comment]
I'm using fish, hence the missing `$`, but if I drop into a bash shell the same errors occur.

**Comment by junglie85** [comment]
I finally managed to get the tests to run. I'm not sure why the above command runs, unless the tests are also running in a Docker container?

I had to bind my local port `9042` when running the scylla image, in addition to the instructions.

I also had to fallback to the default connection string of 127.0.0.1:9042 in the code by not specifying the `SCYLLA_URI` env var when running `cargo test` because the `docker inspect` command was giving me the Docker internal IP.

**Comment by piodul** [comment]
> I finally managed to get the tests to run. I'm not sure why the above command runs, unless the tests are also running in a Docker container?

Apparently, there is a difference between how docker on Linux handles bridge networking vs. MacOS/Windows. On Linux (which I use) the internal address is reachable, while on other OS-es is not.

> 
> I had to bind my local port `9042` when running the scylla image, in addition to the instructions.
> 
> I also had to fallback to the default connection string of 127.0.0.1:9042 in the code by not specifying the `SCYLLA_URI` env var when running `cargo test` because the `docker inspect` command was giving me the Docker internal IP.

I'm wondering why this works. IIUC, the driver establishes the first connection to the given address, reads the topology information - which contains the internal Docker IP of the node - and then connects to the address from the topology information which should not be reachable.

Perhaps the tests should be run in a Docker container, too - so that it is in the same network as Scylla and is able to connect through the internal address.

**Comment by havaker** [comment]
The tests can now be run in the same network as ScyllaDB, thanks to https://github.com/scylladb/scylla-rust-driver/pull/584, https://github.com/scylladb/scylla-rust-driver/pull/479. Invoking `make dockerized-test` should allow you to run our test suite without any problems (this is also described now in our [CONTRIBUTING.md](https://github.com/scylladb/scylla-rust-driver/blob/main/CONTRIBUTING.md#testing) file).

I guess we can close this issue now.

**Comment by piodul** [comment]
> I guess we can close this issue now.

Closing.
